import styles from "./ObjetivosTable.module.css";

function ObjetivosTable({ className }) {
  
  return (
    <div className={`table_container ${className}`}>
      <table className={`custom_table ${styles.ObjetivosTable_container}`}>
        <thead>
          <tr>
            <th>Mês</th>
            <th>Banca Inicial</th>
            <th>Aporte</th>
            <th>Banca Op.</th>
            <th>Stake</th>
            <th>Objetivo</th>
            <th>Lucro</th>
            <th>Saldo Final</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
          <tr>
            <td>1</td>
            <td>0</td>
            <td>R$100,00</td>
            <td>R$100,00</td>
            <td>R$5,00</td>
            <td>R$10,00</td>
            <td>R$10,00</td>
            <td>R$110,00</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}
export default ObjetivosTable;
